version: '3'

services:
  web:
    image: gcr.io/foritu-version1/app-web:app-web
    build: .
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port=8080"
    ports:
      - 8080:8080
    env_file:
      - .env
